on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macos-latest, ubuntu-latest]
        include:
          - os: windows-2019
          - os: macos-latest
          - os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: "3.10"
      - name: Install Conan
        run: pip install conan pytest && conan --version
      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.25.0"
          ninjaVersion: "^1.11.1"
      - name: Run Tests
        run: pytest -rA -v
