on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macos-latest, ubuntu-latest]
        include:
          - os: windows-2019
            ENV_CMAKE: ./activate_run.ps1
          - os: macos-latest
            ENV_CMAKE: source activate_run.sh
          - os: ubuntu-latest
            ENV_CMAKE: source activate_run.sh
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Conan
        run: pip install conan pytest && conan --version
      - name: Install CMake
        run: conan install cmake/3.16.4@ -g=virtualrunenv
      - name: Run Tests
        run: ${{matrix.ENV_CMAKE}} && pytest tests.py -rA -v
